-- Seed data for Camping Trip Planner
-- Generated from packing-list.tsv
-- Run after supabase-schema.sql

INSERT INTO items (name, category, assignee, number, tags) VALUES
  ('books for kids', 'activities', 'Kids', 10, ARRAY['Essential']),
  ('airpods', 'activities', 'Emily', 1, ARRAY['Workout']),
  ('airpods', 'activities', 'Ritchie', 1, ARRAY['Workout']),
  ('headphones', 'activities', 'Kids', 2, ARRAY['Long car rides']),
  ('yotos', 'activities', 'Kids', 2, ARRAY['Long car rides']),
  ('activity books', 'activities', 'Kids', 4, ARRAY['Long car rides']),
  ('books for grownups', 'activities', 'Adults', 2, ARRAY['Essential']),
  ('art supplies', 'activities', 'Kids', 1, ARRAY['Long car rides']),
  ('edibles', 'activities', NULL, 1, ARRAY['Essential']),
  ('ipads', 'activities', 'Kids', 2, ARRAY['Long car rides']),
  ('MPS bands', 'activities', 'Adults', 2, ARRAY['Workout']),
  ('vapes', 'activities', NULL, 1, ARRAY['Essential']),
  ('yoga blocks', 'activities', NULL, 2, ARRAY['Workout']),
  ('flipbelt', 'activities', 'Adults', 1, ARRAY['Workout']),
  ('running shoes', 'shoes', 'Emily', 1, ARRAY['Workout']),
  ('running shoes', 'shoes', 'Ritchie', 1, ARRAY['Workout']),
  ('yoga mats', 'activities', NULL, 2, ARRAY['Workout']),
  ('sun hat', 'clothing', 'Emily', 1, ARRAY['Essential']),
  ('sun hat', 'clothing', 'Ritchie', 1, ARRAY['Essential']),
  ('sun hat', 'clothing', 'Roxy', 1, ARRAY['Essential']),
  ('sun hat', 'clothing', 'Ada', 1, ARRAY['Essential']),
  ('bras', 'clothing', 'Emily', 1, ARRAY['Essential']),
  ('warmest jacket', 'clothing', 'Ritchie', 1, ARRAY['Cold weather', 'Essential']),
  ('warmest jacket', 'clothing', 'Roxy', 1, ARRAY['Cold weather', 'Essential']),
  ('warmest jacket', 'clothing', 'Ada', 1, ARRAY['Cold weather', 'Essential']),
  ('warmest jacket', 'clothing', 'Emily', 1, ARRAY['Cold weather', 'Essential']),
  ('dresses', 'clothing', 'Ada', 2, ARRAY['Essential']),
  ('dresses', 'clothing', 'Roxy', 2, ARRAY['Essential']),
  ('fleece/sweater', 'clothing', 'Ritchie', 1, ARRAY['Essential']),
  ('fleece/sweater', 'clothing', 'Emily', 1, ARRAY['Essential']),
  ('fleece/sweater', 'clothing', 'Roxy', 1, ARRAY['Essential']),
  ('fleece/sweater', 'clothing', 'Ada', 1, ARRAY['Essential']),
  ('pajamas', 'clothing', 'Emily', 1, ARRAY['Essential']),
  ('pants', 'clothing', 'Ritchie', 3, ARRAY['Essential']),
  ('pants', 'clothing', 'Emily', 3, ARRAY['Essential']),
  ('mid layer', 'clothing', 'Ada', 1, ARRAY['Essential']),
  ('mid layer', 'clothing', 'Emily', 1, ARRAY['Essential']),
  ('mid layer', 'clothing', 'Ritchie', 1, ARRAY['Essential']),
  ('mid layer', 'clothing', 'Roxy', 1, ARRAY['Essential']),
  ('long-sleeved base layer', 'clothing', 'Ada', 2, ARRAY['Essential']),
  ('long-sleeved base layer', 'clothing', 'Emily', 2, ARRAY['Essential']),
  ('long-sleeved base layer', 'clothing', 'Ritchie', 2, ARRAY['Essential']),
  ('long-sleeved base layer', 'clothing', 'Roxy', 2, ARRAY['Essential']),
  ('pajamas', 'clothing', 'Ada', 2, ARRAY['Essential']),
  ('pajamas', 'clothing', 'Roxy', 2, ARRAY['Essential']),
  ('pants', 'clothing', 'Ada', 3, ARRAY['Essential']),
  ('pants', 'clothing', 'Roxy', 3, ARRAY['Essential']),
  ('rain jacket', 'clothing', 'Ada', 1, ARRAY['Rain']),
  ('rain jacket', 'clothing', 'Roxy', 1, ARRAY['Rain']),
  ('rain jacket', 'clothing', 'Emily', 1, ARRAY['Rain']),
  ('rain jacket', 'clothing', 'Ritchie', 1, ARRAY['Rain']),
  ('short sleeves/tanks', 'clothing', 'Ada', 3, ARRAY['Essential']),
  ('short sleeves/tanks', 'clothing', 'Emily', 3, ARRAY['Essential']),
  ('short sleeves/tanks', 'clothing', 'Ritchie', 3, ARRAY['Essential']),
  ('short sleeves/tanks', 'clothing', 'Roxy', 3, ARRAY['Essential']),
  ('shorts', 'clothing', 'Ada', 4, ARRAY['Warm weather']),
  ('shorts', 'clothing', 'Emily', 2, ARRAY['Warm weather']),
  ('shorts', 'clothing', 'Ritchie', 2, ARRAY['Warm weather']),
  ('shorts', 'clothing', 'Roxy', 4, ARRAY['Warm weather']),
  ('sleepy bra', 'clothing', 'Emily', 1, ARRAY['Essential']),
  ('socks', 'clothing', 'Emily', 4, ARRAY['Essential']),
  ('socks', 'clothing', 'Ada', 4, ARRAY['Essential']),
  ('socks', 'clothing', 'Ritchie', 4, ARRAY['Essential']),
  ('socks', 'clothing', 'Roxy', 4, ARRAY['Essential']),
  ('swimsuit', 'clothing', 'Ada', 2, ARRAY['Swim']),
  ('swimsuit', 'clothing', 'Emily', 2, ARRAY['Swim']),
  ('swimsuit', 'clothing', 'Ritchie', 2, ARRAY['Swim']),
  ('swimsuit', 'clothing', 'Roxy', 2, ARRAY['Swim']),
  ('goggles', 'activities', 'Ada', 1, ARRAY['Swim']),
  ('goggles', 'activities', 'Roxy', 1, ARRAY['Swim']),
  ('undies', 'clothing', 'Ada', 6, ARRAY['Essential']),
  ('undies', 'clothing', 'Emily', 5, ARRAY['Essential']),
  ('undies', 'clothing', 'Roxy', 5, ARRAY['Essential']),
  ('undies', 'clothing', 'Ritchie', 4, ARRAY['Essential']),
  ('warm hat', 'clothing', 'Ada', 1, ARRAY['Cold weather', 'Essential']),
  ('warm hat', 'clothing', 'Emily', 1, ARRAY['Cold weather', 'Essential']),
  ('warm hat', 'clothing', 'Ritchie', 1, ARRAY['Cold weather', 'Essential']),
  ('warm hat', 'clothing', 'Roxy', 1, ARRAY['Cold weather', 'Essential']),
  ('white hiking shirt', 'clothing', 'Emily', 1, ARRAY['Hiking', 'Warm weather']),
  ('salt & pepper', 'food', NULL, 1, ARRAY['Van gear', 'Essential']),
  ('bug spray', 'gear', NULL, 1, ARRAY['Van gear', 'Essential']),
  ('camping blanket', 'gear', NULL, 2, ARRAY['Van gear', 'Essential']),
  ('camping chairs', 'gear', NULL, 2, ARRAY['Essential']),
  ('double sleeping bag', 'gear', NULL, 1, ARRAY['Van gear', 'Essential']),
  ('expeds', 'gear', NULL, 2, ARRAY['Tent camping']),
  ('firewood', 'gear', NULL, 1, ARRAY['Essential']),
  ('front mat', 'gear', NULL, 1, ARRAY['Essential']),
  ('hammock + straps', 'gear', NULL, 1, ARRAY['Essential']),
  ('head lamps', 'gear', NULL, 4, ARRAY['Van gear', 'Essential']),
  ('hiking daypack', 'gear', 'Emily', 1, ARRAY['Hiking']),
  ('hiking daypack', 'gear', 'Ada', 1, ARRAY['Hiking']),
  ('hiking daypack', 'gear', 'Roxy', 1, ARRAY['Hiking']),
  ('hiking daypack', 'gear', 'Ritchie', 1, ARRAY['Hiking']),
  ('hydration bladder', 'gear', 'Ritchie', 1, ARRAY['Hiking']),
  ('hydration bladder', 'gear', 'Emily', 1, ARRAY['Hiking']),
  ('hydration bladder', 'gear', 'Roxy', 1, ARRAY['Hiking']),
  ('hydration bladder', 'gear', 'Ada', 1, ARRAY['Hiking']),
  ('hot water bottles', 'gear', NULL, 4, ARRAY['Cold weather']),
  ('kids sleeping bags', 'gear', 'Kids', 2, ARRAY['Essential']),
  ('lanterns/string lights', 'gear', NULL, 1, ARRAY['Essential', 'Gray box']),
  ('pillows', 'gear', NULL, 4, ARRAY['Essential']),
  ('propane', 'gear', NULL, 1, ARRAY['Essential']),
  ('stove', 'gear', NULL, 1, ARRAY['Essential']),
  ('tablecloth', 'gear', NULL, 1, ARRAY['Essential', 'Gray box']),
  ('tent', 'gear', NULL, 1, ARRAY['Tent camping']),
  ('bowls', 'kitchen', NULL, 4, ARRAY['Essential', 'Van gear']),
  ('coffee pourer', 'kitchen', NULL, 1, ARRAY['Essential', 'Van gear']),
  ('cutting board', 'kitchen', NULL, 1, ARRAY['Essential']),
  ('dish towels', 'kitchen', NULL, 8, ARRAY['Essential']),
  ('knife', 'kitchen', NULL, 1, ARRAY['Essential', 'Van gear']),
  ('ladel', 'kitchen', NULL, 1, ARRAY['Essential']),
  ('large kettle', 'kitchen', NULL, 1, ARRAY['Essential', 'Van gear']),
  ('marshmallow sticks', 'kitchen', NULL, 2, ARRAY['Essential', 'Gray box']),
  ('paper towel', 'kitchen', NULL, 1, ARRAY['Essential', 'Van gear']),
  ('plastic spatula', 'kitchen', NULL, 1, ARRAY['Essential', 'Van gear']),
  ('plates', 'kitchen', NULL, 7, ARRAY['Essential', 'Van gear']),
  ('pot', 'kitchen', NULL, 1, ARRAY['Essential', 'Van gear']),
  ('silverware', 'kitchen', NULL, 1, ARRAY['Essential', 'Van gear']),
  ('skillet', 'kitchen', NULL, 1, ARRAY['Essential', 'Van gear']),
  ('sponge', 'kitchen', NULL, 1, ARRAY['Essential', 'Van gear']),
  ('tongs', 'kitchen', NULL, 1, ARRAY['Essential', 'Van gear']),
  ('v60 + filters', 'kitchen', NULL, 1, ARRAY['Essential', 'Van gear']),
  ('wine key', 'kitchen', NULL, 1, ARRAY['Essential', 'Van gear']),
  ('yetis', 'kitchen', NULL, 4, ARRAY['Essential', 'Van gear']),
  ('cuddlies', 'personal', 'Ada', 1, ARRAY['Essential']),
  ('cuddlies', 'personal', 'Roxy', 1, ARRAY['Essential']),
  ('earplugs', 'personal', 'Emily', 3, ARRAY['Essential']),
  ('hyena', 'personal', 'Emily', 1, ARRAY['Essential']),
  ('journal', 'personal', 'Emily', 1, ARRAY['Essential']),
  ('journal', 'personal', 'Ritchie', 1, ARRAY['Essential']),
  ('sunglasses', 'personal', 'Emily', 1, ARRAY['Essential']),
  ('sunglasses', 'personal', 'Ritchie', 1, ARRAY['Essential']),
  ('water bottle', 'personal', 'Ada', 1, ARRAY['Essential']),
  ('water bottle', 'personal', 'Emily', 1, ARRAY['Essential']),
  ('water bottle', 'personal', 'Ritchie', 1, ARRAY['Essential']),
  ('water bottle', 'personal', 'Roxy', 1, ARRAY['Essential']),
  ('hiking shoes', 'shoes', 'Emily', 1, ARRAY['Hiking', 'Essential']),
  ('hiking shoes', 'shoes', 'Ritchie', 1, ARRAY['Hiking', 'Essential']),
  ('sandals', 'shoes', 'Ritchie', 1, ARRAY['Warm weather']),
  ('sandals', 'shoes', 'Ada', 1, ARRAY['Warm weather']),
  ('crocs', 'shoes', 'Emily', 1, ARRAY['Warm weather']),
  ('crocs', 'shoes', 'Roxy', 1, ARRAY['Warm weather']),
  ('hiking shoes', 'shoes', 'Ada', 1, ARRAY['Hiking', 'Essential']),
  ('hiking shoes', 'shoes', 'Roxy', 1, ARRAY['Hiking', 'Essential']),
  ('teva slippers', 'shoes', 'Emily', 1, ARRAY['Essential']),
  ('teva slippers', 'shoes', 'Ritchie', 1, ARRAY['Essential']),
  ('benadryl', 'medicine', NULL, 1, ARRAY['Essential']),
  ('adult toothpaste', 'toiletries', NULL, 1, ARRAY['Van gear']),
  ('advil', 'medicine', NULL, 1, ARRAY['Essential']),
  ('aquaphor', 'toiletries', 'Girls', 1, ARRAY['Van gear']),
  ('body lotion', 'toiletries', NULL, 1, ARRAY['Van gear']),
  ('brush', 'toiletries', 'Girls', 1, ARRAY['Van gear']),
  ('children''s benadryl', 'medicine', 'Girls', 1, ARRAY['Essential']),
  ('children''s tylenol', 'medicine', 'Girls', 1, ARRAY['Essential']),
  ('children''s zyrtex', 'medicine', 'Girls', 1, ARRAY['Essential']),
  ('conditioning spray', 'toiletries', 'Girls', 1, ARRAY['Van gear']),
  ('dr. bronners', 'toiletries', NULL, 1, ARRAY['Van gear']),
  ('eyedrops', 'medicine', NULL, 1, ARRAY['Van gear']),
  ('face lotion', 'toiletries', 'Emily', 1, ARRAY['Essential']),
  ('face sunscreen', 'toiletries', 'Emily', 1, ARRAY['Essential']),
  ('face wash', 'toiletries', 'Emily', 1, ARRAY['Essential']),
  ('first aid kit (with tweezers!)', 'medicine', NULL, 1, ARRAY['Van gear']),
  ('floss', 'toiletries', NULL, 1, ARRAY['Van gear']),
  ('hairbands', 'toiletries', 'Girls', 1, ARRAY['Van gear']),
  ('kids toothpaste', 'toiletries', NULL, 1, ARRAY['Van gear']),
  ('makeup', 'toiletries', 'Emily', 1, ARRAY['Essential']),
  ('medication', 'medicine', 'Emily', 1, ARRAY['Essential']),
  ('medication', 'medicine', 'Ritchie', 1, ARRAY['Essential']),
  ('sunscreen', 'toiletries', NULL, 1, ARRAY['Van gear']),
  ('Technu', 'medicine', NULL, 1, ARRAY['Van gear']),
  ('toothbrushes', 'toiletries', NULL, 4, ARRAY['Van gear']),
  ('washcloths', 'toiletries', NULL, 5, ARRAY['Van gear']),
  ('wipes', 'toiletries', NULL, 1, ARRAY['Essential']),
  ('shampoo/conditioner', 'toiletries', NULL, 1, ARRAY['Van gear']),
  ('waterproof shoes/boots', 'shoes', 'Ada', 1, ARRAY['Rain']),
  ('waterproof shoes/boots', 'shoes', 'Roxy', 1, ARRAY['Rain']),
  ('waterproof shoes/boots', 'shoes', 'Emily', 1, ARRAY['Rain']),
  ('waterproof shoes/boots', 'shoes', 'Ritchie', 1, ARRAY['Rain']),
  ('white hiking shirt', 'clothing', 'Ritchie', 1, ARRAY['Warm weather', 'Hiking']),
  ('white hiking shirt', 'clothing', 'Roxy', 1, ARRAY['Warm weather', 'Hiking']),
  ('white hiking shirt', 'clothing', 'Ada', 1, ARRAY['Warm weather', 'Hiking']),
  ('neck lights', 'activities', NULL, 4, ARRAY['Essential']),
  ('charging cords', 'activities', NULL, 4, ARRAY['Essential']),
  ('tampons and pads', 'toiletries', 'Emily', 1, ARRAY['Essential', 'Van gear']),
  ('rain pants', 'clothing', 'Emily', 1, ARRAY['Rain']),
  ('rain pants', 'clothing', 'Ritchie', 1, ARRAY['Rain']),
  ('rain pants', 'clothing', 'Roxy', 1, ARRAY['Rain']),
  ('rain pants', 'clothing', 'Ada', 1, ARRAY['Rain']),
  ('gloves', 'clothing', 'Ritchie', 1, ARRAY['Cold weather']),
  ('gloves', 'clothing', 'Roxy', 1, ARRAY['Cold weather']),
  ('gloves', 'clothing', 'Ada', 1, ARRAY['Cold weather']),
  ('gloves', 'clothing', 'Emily', 1, ARRAY['Cold weather']),
  ('tupperware for lunches', 'kitchen', NULL, 4, ARRAY['Essential', 'Hiking']);
